
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Vibin Vijay  ## put your name
title: 'Graduate Student '  ## your title
location: Santa Cruz , CA


## Social Profiles
linkedin: https://www.linkedin.com/in/vibin-vijay-33570899  ## your linkedin account url
facebook: https://www.facebook.com/vibin.vijay.338  ## your facebook account url



# Update all the sections by editing the files inside _includes folder.
